### ISSUE TITLE
Is webpack still compiling? Can't find main.css in ./dist/manifest.json

### ISSUE THREAD

**Issue by wdeer** [MarsBased/middleman-webpack#1]
So I keep getting the "Is webpack still compiling" error?

	MiddlemanWebpacker::FileLoader::NotFoundError: Can't find main.css in ~/Sites/wdportfolio/dist/manifest.json. Is webpack still compiling?
	/Users/wdeer/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/middleman-webpacker-1.0.0/lib/middleman-webpacker/manifest.rb:15:in `lookup'
	/Users/wdeer/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/middleman-webpacker-1.0.0/lib/middleman-webpacker/helpers.rb:7:in `stylesheet_pack_tag'

I don't have any errors from webpack in my `./config/webpack/development.js` i have:

	//webpack config
    ...
    const extractSASS = new ExtractTextPlugin('./css/[name].css');

    const config = {
      context: path.resolve(__dirname, '../../source/assets'),

      entry: {
        main: './js/main.js'
      },

      output: {
        path: path.resolve(__dirname, '../../dist/assets'),
        filename: './js/[name].js',
      },

      ...
      
      };
      module.exports = config;

and webpack is outputting all assets appropriately in their denoted output directories

from:

- ./source/assets/js
- ./source/assets/css
- ./source/assets/images

outputting to:

- ./dist/assets/js
- ./dist/assets/css
- ./dist/assets/images

and in ./config.rb:

	set :css_dir, 'assets/css'
	set :js_dir, 'assets/js'
	set :images_dir, 'assets/images'
	
	set :stylesheets_base_path, 'assets/css'
	set :javascripts_base_path, 'assets/js'
	set :images_base_path, 'assets/images'

and my ./source/layouts/layout.erb

I have `<%= stylesheet_pack_tag "main" %>` and `<%= javascript_pack_tag "main" %>`

Is there supposed to be another argument passed to the pack tags? as soon as I remove them then there is no error, but then there are obsiously no assets.

Also there is no manifest.json being created in the ./dist/

Thanks in advance!

**Comment by oriolbcn** [comment]
Hi @wdeer thanks for reporting! I think the problem comes from not generating the `manifest.json` file in the first place.

I am reviewing an example Webpack config we use for testing and I see that we are using the `ManifestPlugin` so seems like that is required to work (I'll add it to the README).

Add the following to the `plugins` section of your Webpack config file:

```
new ManifestPlugin({
  publicPath: '/',
  writeToFileEmit: true
})
```

and require at at the beginning with:
```
const ManifestPlugin = require('webpack-manifest-plugin');`
```

You will also need to add the `webpack-manifest-plugin` to `package.json` and install it.

Let's see if this fixes the issue, please report once you have had the chance to try it.

**Comment by wdeer** [comment]
For some reason it still _wasn't_ working when I had the webpack output path as `path: path.resolve(__dirname, '../../dist/assets'),` because it was putting the manifest file in ./dist/assets/ instead of ./dist/ which is where middleman-webpacker was looking for it.

I tried setting the ManifestPlugin to `publicPath: '../'` to fix it, no luck though..

BUUTT, since i don't really _NEED_ my assets to be nested in a directory called assets, i just changed the output path to `path: path.resolve(__dirname, '../../dist'),` and 👌👌👌 all is working swimmingly so far!

`javascript_pack_tag` and `stylesheet_pack_tag` are working perfectly, I don't have any embedded images though so i haven't tried the `image_pack_tag`

🙌 🙌 🙌 Thanks @oriolbcn  for the quick help! 🙌 🙌 🙌

**Comment by oriolbcn** [comment]
Ha! good point, the library is not prepared yet to handle cases where the public path is different than the default.

Glad that you made it work!
